#include "../config.h"
/*
frontier_multi_spreads.h
	set up battle frontier multi battle spreads:
		EVs, IVs, ability type, item, moves, pokeball type, and more!
		
tables to edit:
	gMultiTowerSpread_Milo
	gMultiLegendaryTowerSpread_Milo
	gMultiLittleCupTowerSpread_Milo
	gMultiTowerSpread_Marlon
	gMultiLegendaryTowerSpread_Marlon
	gMultiLittleCupTowerSpread_Marlon
	gMultiTowerSpread_Rival
	gMultiLegendaryTowerSpread_Rival
	gMultiLittleCupTowerSpread_Rival
	gMultiTowerSpread_Jax
	gMultiLegendaryTowerSpread_Jax
	gMultiLittleCupTowerSpread_Jax

*/

extern const u8 sTrainerName_May[];
extern const u8 sTrainerName_Green[];

const struct BattleTowerSpread gMultiTowerSpread_May[] =
{
	{
		.species = SPECIES_CLAYDOL,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_REFLECT,
			MOVE_PSYCHIC,
			MOVE_LIGHTSCREEN,
			MOVE_EARTHPOWER,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_PELIPPER,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_DRIZZLE
		.item = ITEM_DAMP_ROCK,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_HURRICANE,
			MOVE_TAILWIND,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BRELOOM,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_TECHNICIAN
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_MACHPUNCH,
			MOVE_SPORE,
			MOVE_SEEDBOMB,
			MOVE_ROCKTOMB,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_EXPLOUD,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SCRAPPY
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_BOOMBURST,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_RAICHU,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spd = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_LIGHTNINGROD
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_NASTYPLOT,
			MOVE_THUNDERBOLT,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BLAZIKEN,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spAtkEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SPEEDBOOST
		.item = ITEM_BLAZIKENITE,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_FLAREBLITZ,
			MOVE_EARTHQUAKE,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gMultiLegendaryTowerSpread_May[] =
{
	{
		.species = SPECIES_KYOGRE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DRIZZLE
		.item = ITEM_BLUE_ORB,
		.moves =
		{
			MOVE_SURF,
			MOVE_THUNDER,
			MOVE_ICEBEAM,
			MOVE_CALMMIND,
		},
		.ball = BALL_TYPE_DIVE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GROUDON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 136,
		.atkEv = 168,
		.spDefEv = 52,
		.spdEv = 152,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DROUGHT
		.item = ITEM_RED_ORB,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKSLIDE,
			MOVE_SWORDSDANCE,
			MOVE_HEATCRASH,
		},
		.ball = BALL_TYPE_HEAVY_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_RAYQUAZA,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_AIRLOCK
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_DRAGONASCENT,
			MOVE_EARTHQUAKE,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_LATIAS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_REGISTEEL,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.defEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_PROTECT,
			MOVE_TOXIC,
			MOVE_SEISMICTOSS,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_REGICE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_ICEBEAM,
			MOVE_ROCKPOLISH,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gMultiLittleCupTowerSpread_May[] =
{
	{
		.species = SPECIES_LOTAD,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SWIFTSWIM
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_RAINDANCE,
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SHROOMISH,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 196,
		.defEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2, //ABILITY_POISONHEAL
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_BULLETSEED,
			MOVE_DRAINPUNCH,
			MOVE_SWORDSDANCE,
			MOVE_SPORE,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_ARON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_HEADSMASH,
			MOVE_IRONHEAD,
			MOVE_SUPERPOWER,
			MOVE_HEAVYSLAM,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GULPIN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 196,
		.defEv = 12,
		.spAtkEv = 12,
		.spDefEv = 252,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_2, //ABILITY_STICKYHOLD
		.item = ITEM_BLACK_SLUDGE,
		.moves =
		{
			MOVE_VENOSHOCK,
			MOVE_PAINSPLIT,
			MOVE_TOXIC,
			MOVE_AMNESIA,
		},
		.ball = BALL_TYPE_POKE_BALL
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BALTOY,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 36,
		.atkEv = 36,
		.defEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MUDKIP,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 196,
		.defEv = 196,
		.spDefEv = 116,
		.ability = FRONTIER_ABILITY_1, //ABILITY_TORRENT
		.item = ITEM_WATER_GEM,
		.moves =
		{
			MOVE_AQUATAIL,
			MOVE_AVALANCHE,
			MOVE_RETURN,
			MOVE_TOXIC,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gMultiTowerSpread_Green[] =
{
	{
		.species = SPECIES_MAROWAK,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 248,
		.atkEv = 252,
		.defEv = 8,
		.ability = FRONTIER_ABILITY_2, //ABILITY_LIGHTNINGROD
		.item = ITEM_THICK_CLUB,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKSLIDE,
			MOVE_KNOCKOFF,
			MOVE_SWORDSDANCE,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_TANGROWTH,
		.nature = NATURE_SASSY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 252,
		.defEv = 8,
		.spDefEv = 248,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_REGENERATOR
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_KNOCKOFF,
			MOVE_ENERGYBALL,
			MOVE_SLUDGEBOMB,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_CLEFABLE,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_WATERABSORB
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_MOONBLAST,
			MOVE_CALMMIND,
			MOVE_SOFTBOILED,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MAGMORTAR,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_FLASHFIRE
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_THUNDERBOLT,
			MOVE_FOCUSBLAST,
			MOVE_PSYCHIC,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRAGONITE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MULTISCALE
		.item = ITEM_LUM_BERRY,
		.moves =
		{
			MOVE_DRAGONDANCE,
			MOVE_OUTRAGE,
			MOVE_EARTHQUAKE,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BLASTOISE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_TORRENT
		.item = ITEM_BLASTOISINITE,
		.moves =
		{
			MOVE_AURASPHERE,
			MOVE_SURF,
			MOVE_DARKPULSE,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
		.gigantamax = TRUE,
	},
};

const struct BattleTowerSpread gMultiLegendaryTowerSpread_Green[] =
{
	{
		.species = SPECIES_ARTICUNO,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spDefEv = 160,
		.spdEv = 96,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_FREEZEDRY,
			MOVE_HURRICANE,
			MOVE_ROOST,
			MOVE_SUBSTITUTE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_ZAPDOS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 184,
		.spdEv = 72,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_DISCHARGE,
			MOVE_HEATWAVE,
			MOVE_HURRICANE,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MOLTRES,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_HEAVY_DUTY_BOOTS,
		.moves =
		{
			MOVE_FLAMETHROWER,
			MOVE_HURRICANE,
			MOVE_ROOST,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SUICUNE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_SITRUS_BERRY,
		.moves =
		{
			MOVE_SURF,
			MOVE_BLIZZARD,
			MOVE_CALMMIND,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MEW,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SYNCHRONIZE
		.item = ITEM_RED_CARD,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_KNOCKOFF,
			MOVE_FLAREBLITZ,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MEWTWO,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_MEWTWONITE_X,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_CLOSECOMBAT,
			MOVE_STONEEDGE,
			MOVE_EARTHQUAKE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gMultiLittleCupTowerSpread_Green[] =
{
	{
		.species = SPECIES_DIGLETT,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 248,
		.atkEv = 252,
		.defEv = 8,
		.ability = FRONTIER_ABILITY_2, //ABILITY_LIGHTNINGROD
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKSLIDE,
			MOVE_SUCKERPUNCH,
			MOVE_SLASH,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_TANGELA,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 100,
		.spAtkEv = 152,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_REGENERATOR
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_KNOCKOFF,
			MOVE_SLEEPPOWDER,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_CLEFFA,
		.nature = NATURE_HASTY,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 196,
		.spAtkEv = 76,
		.spDefEv = 12,
		.spdEv = 236,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MAGICGUARD
		.item = ITEM_SITRUS_BERRY,
		.moves =
		{
			MOVE_COUNTER,
			MOVE_THUNDERWAVE,
			MOVE_ENDEAVOR,
			MOVE_ENDEAVOR,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MAGBY,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 32,
		.spAtkEv = 236,
		.spdEv = 180,
		.ability = FRONTIER_ABILITY_1, //ABILITY_FLAMEBODY
		.item = ITEM_FIGY_BERRY,
		.moves =
		{
			MOVE_BELLYDRUM,
			MOVE_FIREPUNCH,
			MOVE_MACHPUNCH,
			MOVE_RETURN,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MARVELSCALE
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_EXTREMESPEED,
			MOVE_THUNDERWAVE,
			MOVE_DRAGONRUSH,
			MOVE_IRONTAIL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SQUIRTLE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 128,
		.spAtkEv = 252,
		.spDefEv = 128,
		.ability = FRONTIER_ABILITY_1, //ABILITY_TORRENT
		.item = ITEM_WATER_GEM,
		.moves =
		{
			MOVE_IRONDEFENSE,
			MOVE_FAKEOUT,
			MOVE_BLIZZARD,
			MOVE_SURF,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};
