#include "../config.h"
#include "../../include/global.h"
#include "../../include/new/catching.h"
#include "../../include/new/frontier.h"
#include "../../include/constants/moves.h"
#include "../../include/constants/species.h"
#include "../../include/constants/items.h"
#include "../../include/constants/trainer_classes.h"
/*
frontier_special_trainer_spreads.h
	set up battle frontier species for special trainers, including EVs, IVs, nature, ability, ball type, etc!
	
structs to edit:
	gSpecialTowerSpread_Egypt1 
	gSpecialTowerSpread_Egypt2
	gLegendaryTowerSpread_Egypt1
	gMiddleCupTowerSpread_Egypt1
	gLittleCupTowerSpread_Egypt1
	gLittleCupTowerSpread_Egypt2
	
	gSpecialTowerSpread_May replaced with gSpecialTowerSpread_May
	gLegendaryTowerSpread_May
	gMiddleCupTowerSpread_May
	gLittleCupTowerSpread_May
*/

const struct BattleTowerSpread gSpecialTowerSpread_Egypt1[] =
{
	{
		.species = SPECIES_STARMIE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_ANALYTIC
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_PSYSHOCK,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_STARMIE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_ANALYTIC
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_PSYSHOCK,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARMIE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_ANALYTIC
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SURF,
			MOVE_ICEBEAM,
			MOVE_PSYSHOCK,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles =  TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_VENUSAUR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 180,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_CHLOROPHYLL
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_SLEEPPOWDER,
			MOVE_LEECHSEED,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_VENUSAUR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 180,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_CHLOROPHYLL
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_SLEEPPOWDER,
			MOVE_LEECHSEED,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_VENUSAUR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 180,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_CHLOROPHYLL
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_SLEEPPOWDER,
			MOVE_LEECHSEED,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRAGONITE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MULTISCALE
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_EARTHQUAKE,
			MOVE_EXTREMESPEED,
			MOVE_FIREPUNCH,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_DRAGONITE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MULTISCALE
		.item = ITEM_SALAC_BERRY,
		.moves =
		{
			MOVE_DRAGONPULSE,
			MOVE_THUNDER,
			MOVE_ICEBEAM,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRAGONITE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MULTISCALE
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_EARTHQUAKE,
			MOVE_EXTREMESPEED,
			MOVE_FIREPUNCH,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SCIZOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_TECHNICIAN
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SWORDSDANCE,
			MOVE_BULLETPUNCH,
			MOVE_SUPERPOWER,
			MOVE_BUGBITE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SCIZOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_TECHNICIAN
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SWORDSDANCE,
			MOVE_BULLETPUNCH,
			MOVE_KNOCKOFF,
			MOVE_BUGBITE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_SCIZOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_TECHNICIAN
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SWORDSDANCE,
			MOVE_BULLETPUNCH,
			MOVE_SUPERPOWER,
			MOVE_PURSUIT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_NINETALES,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_DROUGHT
		.item = ITEM_HEAT_ROCK,
		.moves =
		{
			MOVE_SOLARBEAM,
			MOVE_NASTYPLOT,
			MOVE_EXTRASENSORY,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_NINETALES,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_DROUGHT
		.item = ITEM_HEAT_ROCK,
		.moves =
		{
			MOVE_SOLARBEAM,
			MOVE_NASTYPLOT,
			MOVE_EXTRASENSORY,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_NINETALES,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_DROUGHT
		.item = ITEM_HEAT_ROCK,
		.moves =
		{
			MOVE_SOLARBEAM,
			MOVE_NASTYPLOT,
			MOVE_EXTRASENSORY,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SHUCKLE,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 248,
		.defEv = 8,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_STURDY
		.item = ITEM_FLAME_ORB,
		.moves =
		{
			MOVE_INFESTATION,
			MOVE_TOXIC,
			MOVE_ENCORE,
			MOVE_STICKYWEB,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SHUCKLE,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 248,
		.defEv = 8,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_STURDY
		.item = ITEM_FLAME_ORB,
		.moves =
		{
			MOVE_INFESTATION,
			MOVE_TOXIC,
			MOVE_ENCORE,
			MOVE_STICKYWEB,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_SHUCKLE,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 248,
		.defEv = 8,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_STURDY
		.item = ITEM_FLAME_ORB,
		.moves =
		{
			MOVE_INFESTATION,
			MOVE_TOXIC,
			MOVE_ENCORE,
			MOVE_STICKYWEB,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_Egypt2[] =
{
	{
		.species = SPECIES_SUICUNE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spDefEv = 40,
		.spdEv = 216,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_PROTECT,
			MOVE_SCALD,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_SUICUNE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spDefEv = 40,
		.spdEv = 216,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_PROTECT,
			MOVE_SCALD,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SUICUNE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spDefEv = 40,
		.spdEv = 216,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_PROTECT,
			MOVE_SCALD,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles =  TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_VENUSAUR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 180,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_CHLOROPHYLL
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_SLEEPPOWDER,
			MOVE_LEECHSEED,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_VENUSAUR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 180,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_CHLOROPHYLL
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_SLEEPPOWDER,
			MOVE_LEECHSEED,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_VENUSAUR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 180,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_CHLOROPHYLL
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_SLEEPPOWDER,
			MOVE_LEECHSEED,
			MOVE_SLUDGEBOMB,
			MOVE_GIGADRAIN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_LATIOS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_WHITE_HERB,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ICEBEAM,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LATIOS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_WHITE_HERB,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ICEBEAM,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_LATIOS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_WHITE_HERB,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ICEBEAM,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SCIZOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_TECHNICIAN
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SWORDSDANCE,
			MOVE_BULLETPUNCH,
			MOVE_SUPERPOWER,
			MOVE_BUGBITE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SCIZOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_TECHNICIAN
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SWORDSDANCE,
			MOVE_BULLETPUNCH,
			MOVE_KNOCKOFF,
			MOVE_BUGBITE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_SCIZOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_TECHNICIAN
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SWORDSDANCE,
			MOVE_BULLETPUNCH,
			MOVE_SUPERPOWER,
			MOVE_PURSUIT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARAPTOR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_UTURN,
			MOVE_BRAVEBIRD,
			MOVE_QUICKATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARAPTOR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_UTURN,
			MOVE_BRAVEBIRD,
			MOVE_DOUBLEEDGE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_STARAPTOR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_UTURN,
			MOVE_BRAVEBIRD,
			MOVE_GIGAIMPACT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gLegendaryTowerSpread_Egypt1[] =
{
	{
		.species = SPECIES_SUICUNE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spDefEv = 40,
		.spdEv = 216,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_PROTECT,
			MOVE_SCALD,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SUICUNE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spDefEv = 40,
		.spdEv = 216,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_PROTECT,
			MOVE_SCALD,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
		.species = SPECIES_LATIOS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_WHITE_HERB,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ICEBEAM,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
		.species = SPECIES_LATIOS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_WHITE_HERB,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ICEBEAM,
			MOVE_THUNDERBOLT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DARKRAI,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_BADDREAMS
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYPNOSIS,
			MOVE_DARKPULSE,
			MOVE_NASTYPLOT,
			MOVE_SLUDGEBOMB,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DARKRAI,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_BADDREAMS
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYPNOSIS,
			MOVE_DARKPULSE,
			MOVE_NASTYPLOT,
			MOVE_SLUDGEBOMB,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GENESECT,
		.nature = NATURE_HASTY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DOWNLOAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_UTURN,
			MOVE_IRONHEAD,
			MOVE_EXTREMESPEED,
			MOVE_BLAZEKICK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GENESECT,
		.nature = NATURE_HASTY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DOWNLOAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_UTURN,
			MOVE_IRONHEAD,
			MOVE_EXTREMESPEED,
			MOVE_BLAZEKICK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_HEATRAN,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_FLASHFIRE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_FLAMETHROWER,
			MOVE_FLASHCANNON,
			MOVE_EARTHPOWER,
			MOVE_DARKPULSE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_HEATRAN,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 180,
		.spAtkEv = 252,
		.spdEv = 76,
		.ability = FRONTIER_ABILITY_1, //ABILITY_FLASHFIRE
		.item = ITEM_AIR_BALLOON,
		.moves =
		{
			MOVE_HEATWAVE,
			MOVE_EARTHPOWER,
			MOVE_SUBSTITUTE,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_Egypt1[] =
{
	{
		.species = SPECIES_HAUNTER,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_STARAVIA,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_BRAVEBIRD,
			MOVE_DOUBLEEDGE,
			MOVE_UTURN,
			MOVE_QUICKATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_RHYDON,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_SITRUS_BERRY,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_STONEEDGE,
			MOVE_HAMMERARM,
			MOVE_MEGAHORN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_DRAGONAIR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 64,
		.spDefEv = 96,
		.spdEv = 96,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MARVELSCALE
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_WATERFALL,
			MOVE_IRONTAIL,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_ROSELIA,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_MAGNETON,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_MAGNETPULL
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_VOLTSWITCH,
			MOVE_FLASHCANNON,
			MOVE_THUNDERBOLT,
			MOVE_TRIATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_Egypt1[] =
{
	{
		.species = SPECIES_RHYHORN,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 36,
		.atkEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_DRILLRUN,
			MOVE_DOUBLEEDGE,
			MOVE_THUNDERFANG,
			MOVE_FIREFANG,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_RHYHORN,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 36,
		.atkEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LIGHTNINGROD
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_STOMPINGTANTRUM,
			MOVE_ROCKSLIDE,
			MOVE_CRUNCH,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 68,
		.atkEv = 244,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SHEDSKIN
		.item = ITEM_ROOM_SERVICE,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_WATERFALL,
			MOVE_IRONTAIL,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_GENTLE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 32,
		.atkEv = 84,
		.spAtkEv = 196,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MARVELSCALE
		.item = ITEM_EJECT_PACK,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_BODYSLAM,
			MOVE_AQUAJET,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARLY,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 196,
		.atkEv = 236,
		.spdEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_BRAVEBIRD,
			MOVE_UTURN,
			MOVE_FINALGAMBIT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARLY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 76,
		.atkEv = 236,
		.spdEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_BRAVEBIRD,
			MOVE_UTURN,
			MOVE_TAILWIND,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GASTLY,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GASTLY,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MAGNEMITE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_MAGNETPULL
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_VOLTSWITCH,
			MOVE_FLASHCANNON,
			MOVE_THUNDERBOLT,
			MOVE_TRIATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MAGNEMITE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_MAGNETPULL
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_VOLTSWITCH,
			MOVE_FLASHCANNON,
			MOVE_THUNDERBOLT,
			MOVE_TRIATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BUDEW,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BUDEW,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_Egypt2[] =
{
	{
		.species = SPECIES_RHYHORN,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 36,
		.atkEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_DRILLRUN,
			MOVE_DOUBLEEDGE,
			MOVE_THUNDERFANG,
			MOVE_FIREFANG,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_RHYHORN,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 36,
		.atkEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LIGHTNINGROD
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_STOMPINGTANTRUM,
			MOVE_ROCKSLIDE,
			MOVE_CRUNCH,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 68,
		.atkEv = 244,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SHEDSKIN
		.item = ITEM_ROOM_SERVICE,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_WATERFALL,
			MOVE_IRONTAIL,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_GENTLE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 32,
		.atkEv = 84,
		.spAtkEv = 196,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_MARVELSCALE
		.item = ITEM_EJECT_PACK,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_BODYSLAM,
			MOVE_AQUAJET,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARLY,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 0,
		.hpEv = 196,
		.atkEv = 236,
		.spdEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_BRAVEBIRD,
			MOVE_UTURN,
			MOVE_FINALGAMBIT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_STARLY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 76,
		.atkEv = 236,
		.spdEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_RECKLESS
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_BRAVEBIRD,
			MOVE_UTURN,
			MOVE_TAILWIND,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GASTLY,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GASTLY,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MAGNEMITE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_MAGNETPULL
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_VOLTSWITCH,
			MOVE_FLASHCANNON,
			MOVE_THUNDERBOLT,
			MOVE_TRIATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MAGNEMITE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_MAGNETPULL
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_VOLTSWITCH,
			MOVE_FLASHCANNON,
			MOVE_THUNDERBOLT,
			MOVE_TRIATTACK,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BUDEW,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BUDEW,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_May[] =
{
	{
		.species = SPECIES_CLAYDOL,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_STEALTHROCK,
			MOVE_EARTHPOWER,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_CLAYDOL,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
			MOVE_PSYCHIC,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_CLAYDOL,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHTCLAY,
		.moves =
		{
			MOVE_STEALTHROCK,
			MOVE_PSYCHIC,
			MOVE_TOXIC,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles =  TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_PELIPPER,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_DRIZZLE
		.item = ITEM_DAMP_ROCK,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_HURRICANE,
			MOVE_TAILWIND,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_PELIPPER,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_DRIZZLE
		.item = ITEM_DAMP_ROCK,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_HURRICANE,
			MOVE_TAILWIND,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_PELIPPER,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_2, //ABILITY_DRIZZLE
		.item = ITEM_DAMP_ROCK,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_HURRICANE,
			MOVE_TAILWIND,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BRELOOM,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_TECHNICIAN
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_MACHPUNCH,
			MOVE_SPORE,
			MOVE_SEEDBOMB,
			MOVE_ROCKTOMB,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_BRELOOM,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_TECHNICIAN
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_MACHPUNCH,
			MOVE_SPORE,
			MOVE_SEEDBOMB,
			MOVE_ROCKTOMB,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BRELOOM,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 236,
		.spDefEv = 176,
		.spdEv = 96,
		.ability = FRONTIER_ABILITY_2, //ABILITY_POISONHEAL
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_SUBSTITUTE,
			MOVE_SPORE,
			MOVE_LEECHSEED,
			MOVE_FOCUSPUNCH,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_EXPLOUD,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SCRAPPY
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_BOOMBURST,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_EXPLOUD,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SCRAPPY
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_BOOMBURST,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_EXPLOUD,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SCRAPPY
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_BOOMBURST,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
			MOVE_FIREBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_RAICHU,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spd = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_LIGHTNINGROD
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_NASTYPLOT,
			MOVE_THUNDERBOLT,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_RAICHU,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spd = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_LIGHTNINGROD
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_NASTYPLOT,
			MOVE_THUNDERBOLT,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_RAICHU,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spd = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_LIGHTNINGROD
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_NASTYPLOT,
			MOVE_THUNDERBOLT,
			MOVE_SURF,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BLAZIKEN,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spAtkEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SPEEDBOOST
		.item = ITEM_FIGY_BERRY,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_FLAREBLITZ,
			MOVE_EARTHQUAKE,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BLAZIKEN,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spAtkEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SPEEDBOOST
		.item = ITEM_FIGY_BERRY,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_FLAREBLITZ,
			MOVE_EARTHQUAKE,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_BLAZIKEN,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spAtkEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SPEEDBOOST
		.item = ITEM_FIGY_BERRY,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_FLAREBLITZ,
			MOVE_BULKUP,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};

const struct BattleTowerSpread gLegendaryTowerSpread_May[] =
{
	{
		.species = SPECIES_RAYQUAZA,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_AIRLOCK
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_DRAGONASCENT,
			MOVE_EARTHQUAKE,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_RAYQUAZA,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_AIRLOCK
		.item = ITEM_ROSELI_BERRY,
		.moves =
		{
			MOVE_DRAGONASCENT,
			MOVE_EARTHQUAKE,
			MOVE_EXTREMESPEED,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_RAYQUAZA,
		.nature = NATURE_HASTY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_AIRLOCK
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_DRAGONASCENT,
			MOVE_EARTHPOWER,
			MOVE_HYPERVOICE,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_KYOGRE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DRIZZLE
		.item = ITEM_BLUE_ORB,
		.moves =
		{
			MOVE_SURF,
			MOVE_THUNDER,
			MOVE_ICEBEAM,
			MOVE_CALMMIND,
		},
		.ball = BALL_TYPE_DIVE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_KYOGRE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DRIZZLE
		.item = ITEM_BLUE_ORB,
		.moves =
		{
			MOVE_WATERSPOUT,
			MOVE_ORIGINPULSE,
			MOVE_ICEBEAM,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_DIVE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GROUDON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 136,
		.atkEv = 168,
		.spDefEv = 52,
		.spdEv = 152,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DROUGHT
		.item = ITEM_RED_ORB,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKSLIDE,
			MOVE_SWORDSDANCE,
			MOVE_HEATCRASH,
		},
		.ball = BALL_TYPE_HEAVY_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GROUDON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 136,
		.atkEv = 168,
		.spDefEv = 52,
		.spdEv = 152,
		.ability = FRONTIER_ABILITY_1, //ABILITY_DROUGHT
		.item = ITEM_RED_ORB,
		.moves =
		{
			MOVE_PRECIPICEBLADES,
			MOVE_ROCKSLIDE,
			MOVE_SWORDSDANCE,
			MOVE_HEATCRASH,
		},
		.ball = BALL_TYPE_HEAVY_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_LATIAS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LATIAS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_LATIAS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_CALMMIND,
			MOVE_DRACOMETEOR,
			MOVE_PSYSHOCK,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_REGISTEEL,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.defEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_PROTECT,
			MOVE_TOXIC,
			MOVE_SEISMICTOSS,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_REGISTEEL,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.defEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_PROTECT,
			MOVE_TOXIC,
			MOVE_SEISMICTOSS,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_REGISTEEL,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.defEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_PROTECT,
			MOVE_TOXIC,
			MOVE_SEISMICTOSS,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_REGICE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_ICEBEAM,
			MOVE_ROCKPOLISH,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_REGICE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_CLEARBODY
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_ICEBEAM,
			MOVE_ROCKPOLISH,
			MOVE_FOCUSBLAST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_JIRACHI,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SERENEGRACE
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_ZENHEADBUTT,
			MOVE_IRONHEAD,
			MOVE_BODYSLAM,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_May[] =
{
	{
		.species = SPECIES_LOMBRE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SWIFTSWIM
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_RAINDANCE,
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LOMBRE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SWIFTSWIM
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_RAINDANCE,
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LOUDRED,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.SpdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SCRAPPY
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_HYPERVOICE,
			MOVE_OVERHEAT,
			MOVE_BLIZZARD,
			MOVE_EXTRASENSORY,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LOUDRED,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.SpdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_SCRAPPY
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_HYPERVOICE,
			MOVE_OVERHEAT,
			MOVE_BLIZZARD,
			MOVE_EXTRASENSORY,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LAIRON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_HEADSMASH,
			MOVE_IRONHEAD,
			MOVE_SUPERPOWER,
			MOVE_HEAVYSLAM,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_ROSELIA,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_ROSELIA,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_NATURALCURE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_LEECHSEED,
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_DUSCLOPS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_WILLOWISP,
			MOVE_PAINSPLIT,
			MOVE_SEISMICTOSS,
			MOVE_SHADOWSNEAK, 
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
		.species = SPECIES_DUSCLOPS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //ABILITY_PRESSURE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_WILLOWISP,
			MOVE_PAINSPLIT,
			MOVE_SEISMICTOSS,
			MOVE_SHADOWSNEAK, 
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_SHELGON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.defEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_OVERCOAT
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_ZENHEADBUTT,
			MOVE_ROCKSLIDE,
			MOVE_SHADOWCLAW,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_SHELGON,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_OVERCOAT
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_DRAGONRAGE,
			MOVE_TOXIC,
			MOVE_IRONDEFENSE,
			MOVE_REST,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
		.shiny = TRUE,
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_May[] =
{
	{
		.species = SPECIES_LOTAD,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SWIFTSWIM
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_RAINDANCE,
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_LOTAD,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SWIFTSWIM
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_RAINDANCE,
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_LOTAD,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_SWIFTSWIM
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_RAINDANCE,
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_ENERGYBALL,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_SHROOMISH,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 196,
		.defEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2, //ABILITY_POISONHEAL
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_BULLETSEED,
			MOVE_DRAINPUNCH,
			MOVE_SWORDSDANCE,
			MOVE_SPORE,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_SHROOMISH,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 116,
		.atkEv = 196,
		.spDefEv = 36,
		.spdEv = 156,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_QUICKFEET
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_SEEDBOMB,
			MOVE_DOUBLEEDGE,
			MOVE_RETURN,
			MOVE_SUBSTITUTE,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_SHROOMISH,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 116,
		.spAtkEv = 196,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_EFFECTSPORE
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_LEECHSEED,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_ARON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_HEADSMASH,
			MOVE_IRONHEAD,
			MOVE_SUPERPOWER,
			MOVE_HEAVYSLAM,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_ARON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_HEADSMASH,
			MOVE_IRONHEAD,
			MOVE_SUPERPOWER,
			MOVE_HEAVYSLAM,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_ARON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //ABILITY_ROCKHEAD
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_HEADSMASH,
			MOVE_IRONHEAD,
			MOVE_SUPERPOWER,
			MOVE_HEAVYSLAM,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
		.shiny = TRUE,
	},
	{
		.species = SPECIES_GULPIN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 196,
		.defEv = 12,
		.spAtkEv = 12,
		.spDefEv = 252,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_2, //ABILITY_STICKYHOLD
		.item = ITEM_BLACK_SLUDGE,
		.moves =
		{
			MOVE_VENOSHOCK,
			MOVE_PAINSPLIT,
			MOVE_TOXIC,
			MOVE_AMNESIA,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_GULPIN,
		.nature = NATURE_SASSY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 196,
		.atkEv = 12,
		.defEv = 12,
		.spDefEv = 252,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_GLUTTONY
		.item = ITEM_BINDING_BAND,
		.moves =
		{
			MOVE_GUNKSHOT,
			MOVE_INFESTATION,
			MOVE_REST,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_GULPIN,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 252,
		.spDefEv = 60,
		.spdEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LIQUIDOOZE
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_ACIDSPRAY,
			MOVE_YAWN,
			MOVE_DESTINYBOND,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BALTOY,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 36,
		.atkEv = 36,
		.defEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_BALTOY,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 36,
		.spAtkEv = 196,
		.spDefEv = 36,
		.spdEv = 236,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_EARTHPOWER,
			MOVE_PSYCHIC,
			MOVE_SHADOWBALL,
			MOVE_ROCKPOLISH,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_BALTOY,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.defEv = 60,
		.spDefEv = 196,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //ABILITY_LEVITATE
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_ROCKSLIDE,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MUDKIP,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 196,
		.defEv = 196,
		.spDefEv = 116,
		.ability = FRONTIER_ABILITY_1, //ABILITY_TORRENT
		.item = ITEM_WATER_GEM,
		.moves =
		{
			MOVE_AQUATAIL,
			MOVE_AVALANCHE,
			MOVE_RETURN,
			MOVE_TOXIC,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = TRUE,
	},
	{
		.species = SPECIES_MUDKIP,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 196,
		.spAtkEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //ABILITY_TORRENT
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SCALD,
			MOVE_TOXIC,
			MOVE_ATTRACT,
			MOVE_SUBSTITUTE,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = TRUE,
		.forDoubles = FALSE,
		.modifyMovesDoubles = FALSE,
	},
	{
		.species = SPECIES_MUDKIP,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.spdIv = 31,
		.atkEv = 240,
		.defEv = 36,
		.spDefEv = 196,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_HIDDEN, //ABILITY_DAMP
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_ROCKSLIDE,
			MOVE_BODYSLAM,
			MOVE_WIDEGUARD,
		},
		.ball = BALL_TYPE_POKE_BALL,
		.forSingles = FALSE,
		.forDoubles = TRUE,
		.modifyMovesDoubles = FALSE,
	},
};
